language: java
before_install:
- chmod +x gradlew
deploy:
  provider: heroku
  api_key:
    secure: e80P8hdrOjTT6q7ordJQuXHd/acY0f0ijdEZijUfNhO6D2Tv1MrU4E4kKrYxdAGZAn/MTaUYbuSiPLs2QOCWF0pVES+dA628HbfhpJ/B/vF/mcenZAo0ghMrpMl74kb5KLUde9DxTFwYjWU3jvMT+fXFobzki5tlAzpzJWxhGU4BlhWL9M5tXVFSsVy8gIcbgp1tKC29IMRI++aPnh+lbg2M7wtJWkcW7DJj9ife5r+rAbcie5VQUtD2yUrQNGIjp2Hio1ER0qSFsNrdGCLomS2GDolaV3UW48ydzfDygg1hrhsq6+LkSlDP5xRPYo9aN9hurgIDg9+9ZorHwPGzSWviAXkdab/o7Srk7a5ldZnLZMLFqE6E/nhEiuEUsMgs7ZXHePW2YLljH+Rnyz4ZLZyO+V6MsC0YmvNGK+8hxKrLVEy0C6QDqpLcgxc4ugcnqJxL2gXMSzWTJZ4LbJ3viURnYz9NlgfQcA8LQyuE4EqcJ3HUmBSUGj08DYo2yK9tfeCcz+Zbjps8ko0kYJkghQSomNyf94U5nJoq15YX8/BIWP9AipHQxkNhCYNA9bXkxZD+fRR+gxgcCv4fUDczFE23cLvRlO2g0ZLzoW3ZyfEM9oc6wsdcQAlUNiZqTIlQEWFlCIIZXxktPNZ7XMXn5v5bHZceuiTtdvgsuVWIS8o=
  app:
    master: gluggagaigir-staging
    production: gluggagaigir-production

jdk:
  - oraclejdk8
after_success:
  - bash <(curl -s https://codecov.io/bash)
