/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package is.ru.hugb;

import org.junit.Test;
import static org.junit.Assert.*;

public class TicTacToeTest {
    /*@Test 
    public static Boolean testFindAndPlaceInField(){
        //String player, String tempNum, char[][] field
        TicTacToe classUnderTest = new TicTacToe();
        char[][] insertField = new char[3][3];
        int counter = 1;
        for(int i = 0; i < 3; i++){
            for(int j = 0; j < 3; j++){
                insertField[i][j] = (char) (counter+48);
                counter++;
            }
        }
        char[][] returnField = new char[3][3];
        returnField[1][1] = 'X';

        assertEquals(returnField, classUnderTest.findAndPlaceInField("X", "5", insertField));
    }/*

    /*public static char testCheckWinConditions(char[][]field){
        //Setup
        //char[][]field
        //Act
        //Assert
    }*/


}
